version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/vue-resource
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Release
          command: npm run build