version: 2
jobs:
  build:
    docker:
      - image: node:7.9.0
    working_directory: ~/vue-resource
    steps:
      - run: apt-get update && apt-get -y install git
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build Release
          command: yarn run build