version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/vue-resource
    steps:
      - run:
          name: Update Environment
          command: apt-get update && apt-get -y install unzip
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build Release
          command: yarn run build
