version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/vue-resource
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build Release
          command: yarn run build
